#!/bin/bash
#
#
# bash_radio_gr - ακούστε online ραδιόφωνο από το τερματικό
# Copyright (c)2018 Vasilis Niakas and Contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation version 3 of the License.
#
# Please read the file LICENSE and README for more information.
#
#
terms=0
trap ' [ $terms = 1 ] || { terms=1; kill -TERM -$$; };  exit' EXIT INT HUP TERM QUIT 

if [ "$#" -eq "0" ]		    #στην περίπτωση που δε δωθεί όρισμα παίρνει το προκαθορισμένο αρχείο
	then
	stations="gr_stations.txt"
	else
	stations=$1
fi
# echo $stations
# exit 0
player=$(command -v mpv 2>/dev/null || command -v mplayer 2>/dev/null || command -v mpg123 2>/dev/null || echo "1")
# echo $player
if [[ $player = 1 ]];
	then
	echo "Δε βρέθηκε συμβατός player, συμβατοί players είναι οι mplayer και mpv"
	exit
fi

info() {
echo "| Η ώρα είναι "$(date +"%T")" | Ακούτε "$stathmos_name" | Πατήστε Q/q για έξοδο |"
}
echo "---------------------------------------------------------"
echo "bash_radio_gr - ακούστε online ραδιόφωνο από το τερματικό"
echo "---------------------------------------------------------"
echo "https://github.com/billniakas/bash_radio_gr"
echo "---------------------------------------------------------"
num=0 

while IFS='' read -r line || [[ -n "$line" ]]; do
    num=$(( $num + 1 ))
    echo "["$num"]" $line | cut -d "," -f1
done < $stations

# echo $num

while true 
do
echo "---------------------------------------------------------"
read -rp "Διαλέξτε Σταθμό (Q/q για έξοδο): " input

if [[ $input -gt 0 ]] | [[ $input -le $num ]] || [[ $input = "q" ]] || [[ $input = "Q" ]] ;
	then

	   if [[ $input = "q" ]] || [[ $input = "Q" ]] 
   		then
		stathmos_name=$(echo "1")
		stathmos_url=$(echo "1")
		break
           fi
	
	stathmos_name=$(cat $stations | head -n$(( $input )) | tail -n1 | cut -d "," -f1)
	stathmos_url=$(cat $stations | head -n$(( $input )) | tail -n1 | cut -d "," -f2)
	echo 
	echo $stathmos_name
	echo $stathmos_url
	break
	else
	echo "Αριθμός εκτός λίστας"
	
fi
done
#echo $stathmos_name
#echo $stathmos_url
	   if [[ $stathmos_name = "1" ]] | [[ $stathmos_url = "1" ]];
   		then
		echo "Έξοδος..."
           	exit 0
           fi

$player $stathmos_url &> /dev/null &
while true

do 
	   clear 
	   info
	   sleep 0
	   read -n1 -t1 input          # Για μικρότερη αναμονή της read
	   if [[ $input = "q" ]] || [[ $input = "Q" ]] 
   		then
		echo
	        echo "Έξοδος..."
           	break
           fi
done
